version: 0.0
os: linux
files:
  - source: src/
    destination: /var/www/html/
    owner: apache
hooks:
    BeforeInstall:
    - location: script/antes.sh
      timeout: 30
      runas: root
    AfterInstall:
    - lovation: script/depois.sh
      timeout: 30
      runas: root
